apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  labels:
    app: ratings
    version: v1
spec:
  replicas: {{ .Values.ratings.replicas }}
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: {{ .Values.ratings.image }}:{{ .Values.imageVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 9080
        {{- with .Values.ratings.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
