{{- if .Values.connectivityLink.enabled }}
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: bookinfo-dns
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.connectivityLink.gateway.name }}
    namespace: {{ .Values.connectivityLink.gateway.namespace }}
  providerRefs:
    - name: {{ .Values.connectivityLink.dns.providerSecret }}
  healthCheck:
    failureThreshold: {{ .Values.connectivityLink.dns.healthCheck.failureThreshold }}
    interval: {{ .Values.connectivityLink.dns.healthCheck.interval }}
    path: {{ .Values.connectivityLink.dns.healthCheck.path }}
    port: {{ .Values.connectivityLink.dns.healthCheck.port }}
    protocol: {{ .Values.connectivityLink.dns.healthCheck.protocol }}
    allowInsecureCertificate: true
  loadBalancing:
    defaultGeo: {{ .Values.connectivityLink.dns.defaultGeo }}
    geo: {{ .Values.connectivityLink.dns.geo }}
    weight: {{ .Values.connectivityLink.dns.weight }}
{{- end }}
