apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- if .Values.ambient.enabled }}
    istio.io/dataplane-mode: ambient
    istio-discovery: enabled
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
