{{- if .Values.connectivityLink.enabled }}
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: bookinfo-tls
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.connectivityLink.gateway.name }}
    namespace: {{ .Values.connectivityLink.gateway.namespace }}
  issuerRef:
    group: {{ .Values.connectivityLink.tls.issuerGroup }}
    kind: {{ .Values.connectivityLink.tls.issuerKind }}
    name: {{ .Values.connectivityLink.tls.issuerName }}
{{- end }}
